// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqryoaizegmrwlzabtxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxcnlvYWl6ZWdtcndsemFidHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Nzk5NjYsImV4cCI6MjA2NDU1NTk2Nn0.G5VZ3f42E9JMBGB_F0IHmAHIadMCwjqvRxlV4ghKtZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);